version: "3"
services:
  ms-db:
    image: "postgres:14"
    container_name: "ms-template-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms_template_dev
    volumes:
      - /var/lib/postgresql/data

  ms-rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-rabbitmq
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  ms-schdeduler:
    image: mcuadros/ofelia:latest
    container_name: ms-schdeduler
    command: daemon --docker
    depends_on:
      - ms-curl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.ping-me.schedule: "@every 30s"
      ofelia.job-run.ping-me.container: "ms-curl"

  ms-curl:
    image: curlimages/curl:latest
    container_name: ms-curl
    command: "curl -v http://host.docker.internal:3000/healthz"
    extra_hosts:
      - host.docker.internal:host-gateway
