version: "3"
services:
  ms-db:
    image: "postgres:14"
    container_name: "ms-template-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ms_template_dev
    volumes:
      - /var/lib/postgresql/data

  ms-rabbitmq:
    image: rabbitmq:3-management
    container_name: ms-rabbitmq
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  ms-schdeduler:
    image: mcuadros/ofelia:latest
    container_name: ms-schdeduler
    command: daemon --docker
    depends_on:
      - ms-curl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.ping-me.schedule: "@every 30s"
      ofelia.job-run.ping-me.container: "ms-curl"

  ms-curl:
    image: curlimages/curl:latest
    container_name: ms-curl
    command: "curl -v http://host.docker.internal:3000/healthz"
    extra_hosts:
      - host.docker.internal:host-gateway

  ms-jaeger:
    image: "jaegertracing/all-in-one:1.32"
    container_name: "ms-jaeger"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  
  ms-prometheus:
    image: "prom/prometheus"
    container_name: "ms-prometheus"
    ports:
      - "9090:9090"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway" 

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - 3333:3000
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  grafana-storage: