global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nodejs"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["host.docker.internal:3000"]
  - job_name: "rabbitmq"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["ms-rabbitmq:15692"]
