import { Request, Response } from "express"

/**
 * Home page.
 * @route GET /
 */
export const index = (req: Request, res: Response): void => {
  req.logger.debug("Log inside home this is a debug")
  req.logger.info("Log inside home this is a info")
  req.logger.warn("Log inside home this is a warn")
  req.logger.error("Log inside home this is a error")
  res.json({ status: "ok" }).status(200)
}

export const error = (req: Request, res: Response): void => {
  throw new Error(`This is an error generated by the request ${req.method} body: ${JSON.stringify(req.body)}`)
  res.status(200)
}
