/**
 * Generated by postgres-schema-ts
 **/
declare namespace SqlSchema {
  export interface pgmigrations {
    id: number
    name: string
    run_on: Date
  }
  export interface users {
    id: string
    email: string
    date_of_birth: Date | null
    confirmed_at: Date | null
    first_name: string
    last_name: string
    version: number
    updated_at: Date
    created_at: Date
  }
}
